import { mutation } from "./_generated/server";
import { v } from "convex/values";

const DEMO_MEMBERS = [
{ name: "Amara Okafor", role: "CEO & Founder", company: "AgroTech Solutions", industry: "Agriculture", country: "Nigeria", city: "Lagos", bio: "Serial entrepreneur transforming smallholder farming through AI-powered precision agriculture across West Africa.", achievements: "Built a network of 50,000+ farmers using AI crop advisory. Raised $4.2M Series A. Winner, Africa Prize for Engineering Innovation 2023. Forbes Africa 30 Under 30.", currentProjects: "Deploying satellite-based crop monitoring using machine learning for real-time yield prediction across 5 West African countries.", futureProjects: "Launching an AI marketplace connecting African farmers directly to global buyers, cutting out middlemen and increasing farmer income by 300%.", skills: ["AI/ML", "AgTech", "Supply Chain", "Fundraising"], contactEmail: "amara@agrotech.ng", contactPhone: "+234 801 234 5678", linkedIn: "linkedin.com/in/amaraokafor", twitter: "@amaraokafor", seed: 101, gender: "woman" },
{ name: "Kwame Mensah", role: "CTO", company: "FinStack Africa", industry: "Fintech", country: "Ghana", city: "Accra", bio: "Fintech pioneer building the next generation of cross-border payment infrastructure for African businesses.", achievements: "Processed $200M+ in transactions. Built payment infrastructure serving 12 African countries. Ex-Stripe engineer. MIT graduate.", currentProjects: "Building an AI-powered credit scoring system that uses alternative data sources to serve the unbanked population across Africa.", futureProjects: "Creating a pan-African digital currency settlement layer that enables instant, zero-fee business-to-business payments.", skills: ["Blockchain", "Payments", "AI/ML", "System Architecture"], contactEmail: "kwame@finstack.africa", contactPhone: "+233 24 123 4567", linkedIn: "linkedin.com/in/kwamemensah", twitter: "@kwamemensah", seed: 102, gender: "man" },
{ name: "Zara Ndlovu", role: "Founder & CEO", company: "MediAI Africa", industry: "Healthcare", country: "South Africa", city: "Cape Town", bio: "Doctor turned tech entrepreneur, using AI diagnostics to democratize healthcare access across rural Africa.", achievements: "Deployed AI diagnostic tools in 200+ rural clinics. Reduced misdiagnosis rates by 40%. TEDx speaker. WHO Innovation Award recipient.", currentProjects: "Training AI models on African-specific medical datasets to improve diagnostic accuracy for diseases prevalent on the continent.", futureProjects: "Building a telemedicine platform with real-time AI translation supporting 50+ African languages for doctor-patient consultations.", skills: ["Health Tech", "AI Diagnostics", "Telemedicine", "Public Health"], contactEmail: "zara@mediai.co.za", contactPhone: "+27 82 345 6789", linkedIn: "linkedin.com/in/zarandlovu", twitter: "@zarandlovu", seed: 103, gender: "woman" },
{ name: "Tendai Moyo", role: "Managing Director", company: "SolarGrid AI", industry: "Energy", country: "Zimbabwe", city: "Harare", bio: "Clean energy visionary deploying AI-optimized solar microgrids to power off-grid African communities.", achievements: "Powered 100,000+ homes with solar energy. Partnerships with 3 African governments. Bloomberg New Energy Finance Pioneer. Raised $8M.", currentProjects: "Using AI to predict energy demand patterns and optimize solar microgrid distribution across Southern Africa.", futureProjects: "Developing a continent-wide smart grid network using AI and IoT to create Africa's first decentralized renewable energy marketplace.", skills: ["Clean Energy", "IoT", "AI Optimization", "Infrastructure"], contactEmail: "tendai@solargrid.ai", contactPhone: "+263 77 234 5678", linkedIn: "linkedin.com/in/tendaimoyo", twitter: "@tendaimoyo", seed: 104, gender: "man" },
{ name: "Fatima Al-Rashidi", role: "Co-Founder", company: "EduLeap", industry: "Education", country: "Kenya", city: "Nairobi", bio: "EdTech innovator personalizing education through AI for millions of African students.", achievements: "Reached 2M+ students across East Africa. Partnerships with Kenya & Tanzania ministries of education. Y Combinator alumna. Jack Ma Foundation Fellow.", currentProjects: "Building adaptive learning AI that personalizes curricula based on individual student learning patterns and local context.", futureProjects: "Creating an AI-powered skills marketplace matching African youth with global remote work opportunities based on their learning trajectories.", skills: ["EdTech", "AI/ML", "Product Design", "Impact Investing"], contactEmail: "fatima@eduleap.co.ke", contactPhone: "+254 722 123 456", linkedIn: "linkedin.com/in/fatimaalrashidi", twitter: "@fatimaalrashidi", seed: 105, gender: "woman" },
{ name: "Chibueze Eze", role: "Founder", company: "LogiFlow", industry: "Logistics", country: "Nigeria", city: "Abuja", bio: "Logistics entrepreneur revolutionizing last-mile delivery across Africa with AI route optimization.", achievements: "Reduced delivery costs by 45% for 500+ businesses. Operating in 8 Nigerian cities. Techstars alumni. $3.5M raised.", currentProjects: "AI-powered fleet management system that uses real-time traffic and weather data to optimize delivery routes across major African cities.", futureProjects: "Autonomous drone delivery network for medical supplies and essential goods to remote African communities.", skills: ["Logistics", "AI/ML", "Operations", "Drone Technology"], contactEmail: "chibueze@logiflow.ng", contactPhone: "+234 802 345 6789", linkedIn: "linkedin.com/in/chibuezeeze", twitter: "@chibuezeeze", seed: 106, gender: "man" },
{ name: "Naledi Kgosi", role: "CEO", company: "AfroBuild AI", industry: "Construction", country: "Botswana", city: "Gaborone", bio: "PropTech leader using AI and 3D printing to solve Africa's housing crisis with affordable, sustainable construction.", achievements: "Built 500+ affordable homes using AI-optimized designs. Reduced construction costs by 60%. Winner African Development Bank Innovation Prize.", currentProjects: "AI-powered construction planning that optimizes material usage, labor allocation, and project timelines for affordable housing projects.", futureProjects: "Scaling 3D-printed housing using AI design optimization to deliver 10,000 homes annually across Southern Africa.", skills: ["Construction Tech", "3D Printing", "AI Design", "Sustainability"], contactEmail: "naledi@afrobuild.bw", contactPhone: "+267 71 234 567", linkedIn: "linkedin.com/in/naledikgosi", twitter: "@naledikgosi", seed: 107, gender: "woman" },
{ name: "Omar Hassan", role: "Founder & CTO", company: "CyberShield Africa", industry: "Cybersecurity", country: "Egypt", city: "Cairo", bio: "Cybersecurity expert protecting African businesses from emerging digital threats using AI-powered defense systems.", achievements: "Protected 1000+ African businesses from cyber attacks. Developed Africa's first AI threat intelligence platform. Ex-Google Security. PhD in Cybersecurity.", currentProjects: "Building an AI-powered cybersecurity operations center that can detect and respond to threats 100x faster than human analysts.", futureProjects: "Creating a pan-African cybersecurity alliance with shared AI threat intelligence protecting the continent's digital infrastructure.", skills: ["Cybersecurity", "AI/ML", "Cloud Security", "Threat Intelligence"], contactEmail: "omar@cybershield.africa", contactPhone: "+20 100 234 5678", linkedIn: "linkedin.com/in/omarhassan", twitter: "@omarhassan", seed: 108, gender: "man" },
{ name: "Aisha Bello", role: "Managing Partner", company: "AfriVentures AI", industry: "Venture Capital", country: "Nigeria", city: "Lagos", bio: "Impact investor and AI strategist funding the next generation of African tech startups leveraging artificial intelligence.", achievements: "Invested in 40+ AI startups across Africa. Portfolio valued at $150M+. Former McKinsey partner. Harvard Business School MBA. Board member of 3 unicorns.", currentProjects: "Building an AI-powered deal sourcing platform that identifies promising African startups using alternative data signals and predictive analytics.", futureProjects: "Launching a $100M AI-focused Africa fund with an LP base spanning global institutional investors and African sovereign wealth funds.", skills: ["Venture Capital", "AI Strategy", "Due Diligence", "Board Governance"], contactEmail: "aisha@afriventures.com", contactPhone: "+234 803 456 7890", linkedIn: "linkedin.com/in/aishabello", twitter: "@aishabello", seed: 109, gender: "woman" },
{ name: "Samuel Osei", role: "Head of Innovation", company: "AquaAI Ghana", industry: "Water & Sanitation", country: "Ghana", city: "Kumasi", bio: "Water technology innovator using AI and IoT sensors to improve water quality and access across West Africa.", achievements: "Improved water access for 500,000+ people. Deployed AI water quality monitoring in 50+ communities. UNICEF Innovation Award winner.", currentProjects: "AI-powered water distribution optimization that reduces water loss by 35% in African urban centers through predictive leak detection.", futureProjects: "Launching satellite-based groundwater mapping using AI to discover new water sources across the Sahel region.", skills: ["Water Tech", "IoT", "AI/ML", "Environmental Science"], contactEmail: "samuel@aquaai.gh", contactPhone: "+233 20 345 6789", linkedIn: "linkedin.com/in/samuelosei", twitter: "@samuelosei", seed: 110, gender: "man" },
{ name: "Lindiwe Dlamini", role: "CEO", company: "FashionForge AI", industry: "Fashion & Retail", country: "South Africa", city: "Johannesburg", bio: "Fashion tech entrepreneur blending African design heritage with AI to create a global brand and supply chain platform.", achievements: "Built Africa's largest AI-powered fashion marketplace. 100,000+ artisans on platform. Vogue Business Innovation Award. Revenue $12M+.", currentProjects: "AI trend prediction engine that analyzes global fashion data to help African designers create collections aligned with international demand.", futureProjects: "Virtual try-on technology using AI body scanning that enables global customers to buy African fashion with perfect fit guarantees.", skills: ["Fashion Tech", "E-Commerce", "AI/ML", "Supply Chain"], contactEmail: "lindiwe@fashionforge.co.za", contactPhone: "+27 83 456 7890", linkedIn: "linkedin.com/in/lindiwedlamini", twitter: "@lindiwedlamini", seed: 111, gender: "woman" },
{ name: "Ibrahim Diallo", role: "Founder", company: "LinguaAI", industry: "Language Technology", country: "Senegal", city: "Dakar", bio: "NLP researcher building AI language models for African languages to bridge the digital divide.", achievements: "Created AI translation models for 30+ African languages. 5M+ users. Partnership with Google AI. Published 20+ research papers in top NLP conferences.", currentProjects: "Training large language models specifically for African languages using community-sourced data from across the continent.", futureProjects: "Building an AI voice assistant that speaks 100+ African languages, making technology accessible to non-literate populations.", skills: ["NLP", "Machine Learning", "Linguistics", "Research"], contactEmail: "ibrahim@linguaai.sn", contactPhone: "+221 77 234 5678", linkedIn: "linkedin.com/in/ibrahimdiallo", twitter: "@ibrahimdiallo", seed: 112, gender: "man" },
{ name: "Grace Wanjiku", role: "COO", company: "TalentBridge Africa", industry: "Human Resources", country: "Kenya", city: "Nairobi", bio: "HR tech innovator connecting African talent with global opportunities through AI-powered matching algorithms.", achievements: "Placed 25,000+ African professionals in global roles. Partnerships with 200+ Fortune 500 companies. Endeavor Entrepreneur.", currentProjects: "AI talent matching platform that goes beyond resumes to assess cultural fit, growth potential, and skill transferability.", futureProjects: "AI-powered career coaching platform that provides personalized upskilling recommendations for African professionals.", skills: ["HR Tech", "AI Matching", "Talent Management", "Global Partnerships"], contactEmail: "grace@talentbridge.africa", contactPhone: "+254 733 234 567", linkedIn: "linkedin.com/in/gracewanjiku", twitter: "@gracewanjiku", seed: 113, gender: "woman" },
{ name: "Moussa Traoré", role: "Technical Director", company: "MineAI", industry: "Mining", country: "Mali", city: "Bamako", bio: "Mining technology pioneer using AI and drones to make mineral exploration safer, faster, and more environmentally responsible.", achievements: "Discovered 3 new mineral deposits using AI. Reduced exploration costs by 70%. Partnerships with 5 mining companies. PhD Geology.", currentProjects: "AI-powered geological analysis using satellite imagery and drone data to identify mineral deposits without invasive exploration.", futureProjects: "Robotic mining systems guided by AI that can extract minerals with minimal environmental impact and maximum worker safety.", skills: ["Mining Tech", "Geospatial AI", "Drone Technology", "Geology"], contactEmail: "moussa@mineai.ml", contactPhone: "+223 76 234 5678", linkedIn: "linkedin.com/in/moussatraore", twitter: "@moussatraore", seed: 114, gender: "man" },
{ name: "Amina Yusuf", role: "Founder & CEO", company: "InsureAI Africa", industry: "Insurance", country: "Tanzania", city: "Dar es Salaam", bio: "Insurtech founder making insurance accessible and affordable for millions of underserved Africans using AI risk models.", achievements: "Insured 3M+ previously uninsured Africans. Processing 50,000+ claims monthly with AI. Finalist Global Insurtech 100. $6M Series A.", currentProjects: "Microinsurance products powered by AI that can underwrite policies in seconds using mobile phone data and satellite imagery.", futureProjects: "Climate insurance for African farmers using AI weather prediction and blockchain smart contracts for instant payouts.", skills: ["Insurtech", "AI Risk Models", "Microinsurance", "Product Design"], contactEmail: "amina@insureai.co.tz", contactPhone: "+255 784 234 567", linkedIn: "linkedin.com/in/aminayusuf", twitter: "@aminayusuf", seed: 115, gender: "woman" },
{ name: "Jean-Pierre Habimana", role: "CEO", company: "DroneServe Rwanda", industry: "Drone Technology", country: "Rwanda", city: "Kigali", bio: "Drone logistics leader partnering with the Rwandan government to build Africa's most advanced aerial delivery network.", achievements: "Completed 100,000+ drone deliveries. Government partnership for national drone corridor. World Economic Forum Technology Pioneer.", currentProjects: "AI-powered autonomous drone swarm technology for simultaneous multi-point delivery of medical supplies across East Africa.", futureProjects: "Building Africa's first urban air mobility network with AI traffic management for cargo and eventually passenger drones.", skills: ["Drone Tech", "AI Navigation", "Logistics", "Aviation"], contactEmail: "jp@droneserve.rw", contactPhone: "+250 788 234 567", linkedIn: "linkedin.com/in/jphabimana", twitter: "@jphabimana", seed: 116, gender: "man" },
{ name: "Thandiwe Phiri", role: "Chief Data Scientist", company: "DataVault Zambia", industry: "Data Analytics", country: "Zambia", city: "Lusaka", bio: "Data science leader building Africa's first sovereign data infrastructure and AI analytics platform.", achievements: "Built data platforms for 5 African governments. Processed petabytes of African economic data. Stanford PhD. Google AI Research alumna.", currentProjects: "Building a pan-African data lake that enables governments and businesses to make AI-driven decisions using continent-specific datasets.", futureProjects: "Creating an African AI research lab focused on developing models that understand African economic, social, and cultural contexts.", skills: ["Data Science", "AI/ML", "Cloud Infrastructure", "Government Tech"], contactEmail: "thandiwe@datavault.zm", contactPhone: "+260 96 234 5678", linkedIn: "linkedin.com/in/thandiwephiri", twitter: "@thandiwephiri", seed: 117, gender: "woman" },
{ name: "Kofi Asante", role: "Founder", company: "AgriMarket AI", industry: "Agriculture", country: "Ghana", city: "Tamale", bio: "Agricultural marketplace innovator connecting northern Ghana's farmers to markets using AI price prediction and logistics.", achievements: "Connected 30,000+ farmers to premium markets. Increased farmer incomes by 200%. USAID partnership. Ashoka Fellow.", currentProjects: "AI-powered commodity price forecasting that helps farmers decide optimal harvest timing and market selection.", futureProjects: "Blockchain-verified provenance tracking combined with AI quality grading for premium African agricultural exports.", skills: ["AgTech", "Marketplace", "AI Pricing", "Rural Development"], contactEmail: "kofi@agrimarket.gh", contactPhone: "+233 24 567 8901", linkedIn: "linkedin.com/in/kofiasante", twitter: "@kofiasante", seed: 118, gender: "man" },
{ name: "Nadia Benali", role: "VP Engineering", company: "SmartCity Maroc", industry: "Smart Cities", country: "Morocco", city: "Casablanca", bio: "Smart city architect designing AI-powered urban infrastructure solutions for rapidly growing African cities.", achievements: "Led smart city projects in 3 Moroccan cities. Reduced traffic congestion by 30% using AI. Partnership with Huawei. IEEE Fellow.", currentProjects: "AI traffic management system that uses computer vision and predictive analytics to optimize urban mobility across African cities.", futureProjects: "Building a digital twin platform for African cities that uses AI to simulate and optimize urban planning decisions.", skills: ["Smart Cities", "Computer Vision", "Urban Planning", "IoT"], contactEmail: "nadia@smartcity.ma", contactPhone: "+212 661 234 567", linkedIn: "linkedin.com/in/nadiabenali", twitter: "@nadiabenali", seed: 119, gender: "woman" },
{ name: "Patrick Mugisha", role: "Co-Founder & CEO", company: "BankBot Uganda", industry: "Fintech", country: "Uganda", city: "Kampala", bio: "Mobile banking innovator building AI-powered financial services for Uganda's growing digital economy.", achievements: "500,000+ active users. Processing $50M monthly. Partnership with Bank of Uganda. Visa Everywhere Initiative winner.", currentProjects: "AI chatbot financial advisor that helps micro-entrepreneurs manage cash flow, access credit, and make investment decisions via USSD and WhatsApp.", futureProjects: "Decentralized lending protocol using AI credit scoring that enables peer-to-peer lending across East African borders.", skills: ["Mobile Banking", "AI Chatbots", "USSD", "Financial Inclusion"], contactEmail: "patrick@bankbot.ug", contactPhone: "+256 772 234 567", linkedIn: "linkedin.com/in/patrickmugisha", twitter: "@patrickmugisha", seed: 120, gender: "man" },
{ name: "Sade Adeyemi", role: "Creative Director & Founder", company: "AfriCreate Studios", industry: "Creative & Media", country: "Nigeria", city: "Lagos", bio: "Creative tech entrepreneur using AI to amplify African storytelling and content creation for global audiences.", achievements: "Produced AI-assisted content reaching 50M+ viewers. Netflix partnership for African content. Cannes Lions Africa Award.", currentProjects: "AI-powered content creation suite that helps African creators produce world-class video, animation, and music content.", futureProjects: "Virtual production studio using AI and volumetric capture to create Hollywood-quality African films at 10% of traditional cost.", skills: ["Creative Tech", "AI Content", "Film Production", "Storytelling"], contactEmail: "sade@africreate.ng", contactPhone: "+234 805 678 9012", linkedIn: "linkedin.com/in/sadeadeyemi", twitter: "@sadeadeyemi", seed: 121, gender: "woman" },
{ name: "David Kimani", role: "Lead Architect", company: "CloudAfrica", industry: "Cloud Computing", country: "Kenya", city: "Nairobi", bio: "Cloud infrastructure leader building Africa's most reliable and affordable cloud computing platform.", achievements: "Launched 3 data centers across East Africa. 10,000+ business customers. AWS Advanced Partner. $15M raised.", currentProjects: "AI-powered cloud resource optimization that automatically scales infrastructure based on usage patterns, reducing costs by 40%.", futureProjects: "Edge computing network across Africa enabling low-latency AI inference at the edge for real-time applications.", skills: ["Cloud Computing", "DevOps", "AI Infrastructure", "Data Centers"], contactEmail: "david@cloudafrica.co.ke", contactPhone: "+254 724 567 890", linkedIn: "linkedin.com/in/davidkimani", twitter: "@davidkimani", seed: 122, gender: "man" },
{ name: "Mariama Camara", role: "Founder", company: "JusticeAI", industry: "Legal Tech", country: "Guinea", city: "Conakry", bio: "Legal tech pioneer using AI to democratize access to justice and legal services across francophone Africa.", achievements: "Provided free AI legal assistance to 100,000+ people. Partnerships with 8 African bar associations. Oxford Rhodes Scholar.", currentProjects: "AI-powered legal document analysis that helps small businesses understand contracts and regulatory requirements in local languages.", futureProjects: "Building an AI arbitration platform for cross-border African trade disputes that can resolve cases in days instead of years.", skills: ["Legal Tech", "NLP", "Access to Justice", "Policy"], contactEmail: "mariama@justiceai.gn", contactPhone: "+224 622 234 567", linkedIn: "linkedin.com/in/mariamacamara", twitter: "@mariamacamara", seed: 123, gender: "woman" },
{ name: "Thabo Nkosi", role: "CEO", company: "SportAI Africa", industry: "Sports Technology", country: "South Africa", city: "Durban", bio: "Sports tech innovator using AI to discover, develop, and promote African athletic talent globally.", achievements: "Scouted 500+ athletes using AI. Partnerships with Premier League clubs. 50+ athletes placed in professional leagues globally.", currentProjects: "AI-powered athletic performance analysis using computer vision that identifies potential talent from grassroots level competitions.", futureProjects: "Virtual sports academy using AI coaching that provides world-class training to African athletes regardless of their location.", skills: ["Sports Tech", "Computer Vision", "Talent Analytics", "Partnerships"], contactEmail: "thabo@sportai.co.za", contactPhone: "+27 84 567 8901", linkedIn: "linkedin.com/in/thabonkosi", twitter: "@thabonkosi", seed: 124, gender: "man" },
{ name: "Esther Ochieng", role: "Co-Founder", company: "WasteWise AI", industry: "Waste Management", country: "Kenya", city: "Kisumu", bio: "Circular economy champion using AI to transform waste management and recycling across East African cities.", achievements: "Diverted 50,000+ tons from landfills. Created 2,000+ green jobs. UN Environment Programme award. Circular Economy 100 member.", currentProjects: "AI-powered waste sorting robots and smart collection route optimization reducing collection costs by 50% in urban areas.", futureProjects: "Building an AI-driven circular economy platform that matches industrial waste producers with recyclers across Africa.", skills: ["Circular Economy", "AI Robotics", "Waste Tech", "Sustainability"], contactEmail: "esther@wastewise.co.ke", contactPhone: "+254 735 678 901", linkedIn: "linkedin.com/in/estherochieng", twitter: "@estherochieng", seed: 125, gender: "woman" },
{ name: "Abdelrahman Samir", role: "CTO", company: "PropTech Cairo", industry: "Real Estate", country: "Egypt", city: "Cairo", bio: "Real estate tech leader using AI to transform property valuation, management, and investment across North Africa.", achievements: "AI-valued $5B+ in real estate assets. 50,000+ property listings optimized by AI. Top 50 PropTech Companies globally.", currentProjects: "AI property valuation engine that provides instant, accurate valuations using satellite imagery, market data, and predictive analytics.", futureProjects: "Fractional real estate investment platform using AI portfolio optimization, making property investment accessible to all Africans.", skills: ["PropTech", "AI Valuation", "Real Estate", "Investment"], contactEmail: "abdel@proptechcairo.eg", contactPhone: "+20 101 567 8901", linkedIn: "linkedin.com/in/abdelrahmansamir", twitter: "@abdelsamir", seed: 126, gender: "man" },
{ name: "Blessing Okonkwo", role: "Founder & CEO", company: "HealthBot Nigeria", industry: "Healthcare", country: "Nigeria", city: "Port Harcourt", bio: "Digital health entrepreneur building AI-powered health assistants serving millions of Nigerians via WhatsApp.", achievements: "3M+ monthly active users. Partnered with Nigerian Federal Ministry of Health. Google for Startups Accelerator. $2.8M seed round.", currentProjects: "AI symptom checker and health advisor accessible via WhatsApp in Pidgin English, Yoruba, Hausa, and Igbo.", futureProjects: "AI-powered drug interaction checker and personalized medicine recommendations based on African genetic profiles.", skills: ["Digital Health", "AI Chatbots", "WhatsApp Business", "Public Health"], contactEmail: "blessing@healthbot.ng", contactPhone: "+234 806 789 0123", linkedIn: "linkedin.com/in/blessingokonkwo", twitter: "@blessingokonkwo", seed: 127, gender: "woman" },
{ name: "Youssef El Mansouri", role: "Director of AI", company: "TourismAI Morocco", industry: "Tourism", country: "Morocco", city: "Marrakech", bio: "Tourism tech innovator using AI to personalize travel experiences and boost sustainable tourism across Africa.", achievements: "AI platform serving 2M+ tourists annually. Revenue $8M+. Partnership with Moroccan National Tourism Office. World Travel Awards.", currentProjects: "AI-powered personalized itinerary generator that creates custom African travel experiences based on preferences, budget, and sustainability goals.", futureProjects: "AR/AI-powered cultural heritage preservation and virtual tourism platform showcasing Africa's 50+ UNESCO World Heritage sites.", skills: ["Tourism Tech", "AI Personalization", "AR/VR", "Sustainability"], contactEmail: "youssef@tourismai.ma", contactPhone: "+212 662 345 678", linkedIn: "linkedin.com/in/youssefelmansouri", twitter: "@youssefmansouri", seed: 128, gender: "man" },
{ name: "Tigist Bekele", role: "CEO", company: "CoffeeChain AI", industry: "Agriculture", country: "Ethiopia", city: "Addis Ababa", bio: "Agricultural blockchain pioneer ensuring Ethiopian coffee farmers get fair prices through AI quality grading and supply chain transparency.", achievements: "Connected 20,000+ coffee farmers to premium markets. Increased farmer income by 250%. Featured in Bloomberg & Financial Times.", currentProjects: "AI coffee bean quality grading using computer vision that enables instant, objective quality assessment at farm level.", futureProjects: "End-to-end AI supply chain platform for African specialty crops connecting farmers directly to international specialty buyers.", skills: ["AgTech", "Blockchain", "Computer Vision", "Trade"], contactEmail: "tigist@coffeechain.et", contactPhone: "+251 911 234 567", linkedIn: "linkedin.com/in/tigistbekele", twitter: "@tigistbekele", seed: 129, gender: "woman" },
{ name: "Mamadou Diop", role: "Founder", company: "FishAI Senegal", industry: "Fisheries", country: "Senegal", city: "Saint-Louis", bio: "Marine technology innovator using AI and satellite data to protect West African fisheries while improving fisher livelihoods.", achievements: "Monitoring 10,000km of coastline. Reduced illegal fishing by 60% in monitored zones. FAO partnership. Blue Economy Champion.", currentProjects: "AI-powered illegal fishing detection using satellite imagery and vessel tracking data to protect African marine resources.", futureProjects: "Predictive fish stock modeling using AI that enables sustainable fishing quotas and marine protected area planning.", skills: ["Marine Tech", "Satellite AI", "Sustainability", "Policy"], contactEmail: "mamadou@fishai.sn", contactPhone: "+221 78 345 6789", linkedIn: "linkedin.com/in/mamadoudiop", twitter: "@mamadoudiop", seed: 130, gender: "man" },
{ name: "Ruth Akinyi", role: "VP Product", company: "RetailAI East Africa", industry: "Retail", country: "Kenya", city: "Mombasa", bio: "Retail tech strategist using AI to transform informal markets and retail operations across East Africa.", achievements: "Digitized 15,000+ informal retailers. AI-powered inventory management reducing stockouts by 70%. Microsoft AI for Good partner.", currentProjects: "AI demand forecasting for informal retailers that predicts what products to stock based on local events, weather, and seasonal patterns.", futureProjects: "Cashierless checkout technology adapted for African informal markets using computer vision and mobile payments.", skills: ["Retail Tech", "AI Forecasting", "Product Management", "Informal Markets"], contactEmail: "ruth@retailai.co.ke", contactPhone: "+254 745 789 012", linkedIn: "linkedin.com/in/ruthakinyi", twitter: "@ruthakinyi", seed: 131, gender: "woman" },
{ name: "Nelson Chanda", role: "Founder & CEO", company: "TransportAI Zambia", industry: "Transportation", country: "Zambia", city: "Lusaka", bio: "Transport tech entrepreneur building AI-powered public transit solutions for African cities.", achievements: "Optimized bus routes serving 2M+ daily commuters. Reduced average commute time by 25%. Smart Africa Alliance member.", currentProjects: "AI real-time transit tracking and route optimization that improves public transport reliability across Zambian cities.", futureProjects: "Autonomous electric minibus network for African cities using AI navigation adapted to local road conditions.", skills: ["Transport Tech", "AI Routing", "Urban Mobility", "Electric Vehicles"], contactEmail: "nelson@transportai.zm", contactPhone: "+260 97 345 6789", linkedIn: "linkedin.com/in/nelsonchanda", twitter: "@nelsonchanda", seed: 132, gender: "man" },
{ name: "Ama Boateng", role: "Chief Scientist", company: "BioTech Ghana", industry: "Biotechnology", country: "Ghana", city: "Accra", bio: "Biotech researcher using AI to accelerate drug discovery for tropical diseases that disproportionately affect Africans.", achievements: "Discovered 3 potential drug candidates using AI. Published in Nature and Science. Gates Foundation grant recipient. Oxford DPhil.", currentProjects: "AI-powered virtual screening platform that identifies potential drug compounds for neglected tropical diseases in weeks instead of years.", futureProjects: "Pan-African genomics database with AI analysis tools to enable precision medicine tailored to African genetic diversity.", skills: ["Biotech", "AI Drug Discovery", "Genomics", "Research"], contactEmail: "ama@biotechghana.org", contactPhone: "+233 27 456 7890", linkedIn: "linkedin.com/in/amaboateng", twitter: "@amaboateng", seed: 133, gender: "woman" },
{ name: "Olusegun Bakare", role: "Managing Director", company: "MediaAI Nigeria", industry: "Media & Entertainment", country: "Nigeria", city: "Lagos", bio: "Media tech executive using AI to transform African content distribution and monetization globally.", achievements: "Platform distributes content to 100M+ viewers. Nollywood AI recommendation engine. $10M revenue. African Media Leader of the Year.", currentProjects: "AI-powered content recommendation engine specifically trained on African viewing preferences and cultural contexts.", futureProjects: "AI-generated African animation studio producing content in multiple African languages at scale for global platforms.", skills: ["Media Tech", "AI Recommendation", "Content Distribution", "Monetization"], contactEmail: "segun@mediaai.ng", contactPhone: "+234 807 890 1234", linkedIn: "linkedin.com/in/olusegumbakare", twitter: "@segunbakare", seed: 134, gender: "man" },
{ name: "Fatoumata Diallo", role: "Founder", company: "TextileAI", industry: "Manufacturing", country: "Ivory Coast", city: "Abidjan", bio: "Manufacturing innovator using AI quality control and supply chain optimization to revitalize African textile manufacturing.", achievements: "Reduced defect rates by 80% using AI vision. 5 factories optimized. African Industrialization Award. Revenue $6M+.", currentProjects: "AI-powered quality control using computer vision that inspects textiles in real-time, detecting defects invisible to the human eye.", futureProjects: "AI-optimized textile recycling facility that sorts, processes, and repurposes fabric waste into new materials.", skills: ["Manufacturing", "Computer Vision", "Quality Control", "Sustainability"], contactEmail: "fatoumata@textileai.ci", contactPhone: "+225 07 234 5678", linkedIn: "linkedin.com/in/fatoumatadiallo", twitter: "@fatoumatadiallo", seed: 135, gender: "woman" },
{ name: "Godwin Emeka", role: "Co-Founder", company: "LegalEase Africa", industry: "Legal Tech", country: "Nigeria", city: "Enugu", bio: "Legal AI developer creating tools that make legal compliance simple and affordable for African SMEs.", achievements: "Serving 20,000+ SMEs. AI contract review saving businesses $5M+ in legal fees annually. LegalTech Africa Award winner.", currentProjects: "AI-powered regulatory compliance tool that automatically tracks and alerts businesses about relevant legal changes across 20+ African jurisdictions.", futureProjects: "AI legal assistant that can draft, review, and negotiate contracts in multiple African legal traditions and languages.", skills: ["Legal Tech", "NLP", "Compliance", "SME Solutions"], contactEmail: "godwin@legalease.africa", contactPhone: "+234 808 901 2345", linkedIn: "linkedin.com/in/godwinemeka", twitter: "@godwinemeka", seed: 136, gender: "man" },
{ name: "Wanjiru Kamau", role: "Executive Director", company: "GreenTech Kenya", industry: "Environmental Tech", country: "Kenya", city: "Nakuru", bio: "Environmental tech leader using AI satellite monitoring to protect African forests and biodiversity.", achievements: "Monitoring 5M hectares of forest. AI deforestation alerts deployed in 6 countries. UNEP Champion of the Earth finalist.", currentProjects: "Real-time AI deforestation monitoring using satellite imagery that alerts rangers and authorities within minutes of illegal activity.", futureProjects: "Carbon credit marketplace using AI-verified carbon sequestration data from African reforestation projects.", skills: ["Environmental Tech", "Satellite AI", "Conservation", "Carbon Markets"], contactEmail: "wanjiru@greentech.co.ke", contactPhone: "+254 756 890 123", linkedIn: "linkedin.com/in/wanjirukamau", twitter: "@wanjirukamau", seed: 137, gender: "woman" },
{ name: "Emad Saleh", role: "Founder & CEO", company: "ConstructBot Egypt", industry: "Construction", country: "Egypt", city: "Alexandria", bio: "Construction robotics pioneer using AI-guided robots to accelerate infrastructure development across North Africa.", achievements: "Deployed AI construction robots on 50+ projects. Reduced construction time by 40%. $7M Series A. Arab Innovation Award.", currentProjects: "AI-powered construction site monitoring using drones and computer vision that tracks progress and identifies safety hazards.", futureProjects: "Fully autonomous AI-controlled construction robots capable of building standard housing units with minimal human supervision.", skills: ["Construction Robotics", "Computer Vision", "AI Safety", "Infrastructure"], contactEmail: "emad@constructbot.eg", contactPhone: "+20 102 678 9012", linkedIn: "linkedin.com/in/emadsaleh", twitter: "@emadsaleh", seed: 138, gender: "man" },
{ name: "Ngozi Ibe", role: "Head of Strategy", company: "PaySmartAI", industry: "Fintech", country: "Nigeria", city: "Kano", bio: "Financial strategist building AI-powered payment fraud detection systems protecting African digital transactions.", achievements: "Prevented $200M+ in fraud. Serving 50+ African banks. AI detecting fraud with 99.7% accuracy. Certified Anti-Fraud Expert.", currentProjects: "Real-time AI fraud detection engine that analyzes transaction patterns across African payment networks to prevent losses.", futureProjects: "Federated AI learning network where African banks collaboratively train fraud detection models without sharing sensitive customer data.", skills: ["Fraud Detection", "AI/ML", "Banking", "Risk Management"], contactEmail: "ngozi@paysmart.ng", contactPhone: "+234 809 012 3456", linkedIn: "linkedin.com/in/ngoziibe", twitter: "@ngoziibe", seed: 139, gender: "woman" },
{ name: "Tumelo Kekana", role: "CEO", company: "EdAI Tutors", industry: "Education", country: "South Africa", city: "Pretoria", bio: "EdTech founder creating AI tutoring systems that provide personalized education in all 11 South African official languages.", achievements: "200,000+ students using AI tutors. Improved pass rates by 35%. Department of Education partnership. Mandela Fellow.", currentProjects: "Multilingual AI tutoring platform that adapts teaching methods to each student's learning style and language preference.", futureProjects: "AI-powered vocational training platform preparing African youth for Industry 4.0 jobs with hands-on virtual simulations.", skills: ["EdTech", "NLP", "Multilingual AI", "Curriculum Design"], contactEmail: "tumelo@edaitutors.co.za", contactPhone: "+27 76 789 0123", linkedIn: "linkedin.com/in/tumelokekana", twitter: "@tumelokekana", seed: 140, gender: "man" },
{ name: "Halima Abubakar", role: "Founder", company: "NutrAI", industry: "Food & Nutrition", country: "Nigeria", city: "Kaduna", bio: "Food tech innovator using AI to combat malnutrition and optimize food production across Northern Nigeria and the Sahel.", achievements: "AI nutrition programs reaching 1M+ children. Partnership with WFP and UNICEF. Global Food Innovation Award. TED Fellow.", currentProjects: "AI-powered nutrition assessment tool using smartphone photos to detect malnutrition indicators in children under 5.", futureProjects: "AI-optimized food production system that maximizes nutritional output per hectare using precision agriculture in semi-arid regions.", skills: ["Food Tech", "AI Nutrition", "Computer Vision", "Public Health"], contactEmail: "halima@nutrai.ng", contactPhone: "+234 810 123 4567", linkedIn: "linkedin.com/in/halimaabubakar", twitter: "@halimaabubakar", seed: 141, gender: "woman" },
{ name: "Jacques Ndayisaba", role: "CTO", company: "SmartFarm Rwanda", industry: "Agriculture", country: "Rwanda", city: "Kigali", bio: "Precision agriculture engineer using AI drones and sensors to optimize crop yields for Rwandan coffee and tea farmers.", achievements: "Increased yields by 45% for 10,000+ farmers. Government smart agriculture partnership. MIT Technology Review Innovator Under 35.", currentProjects: "AI crop health monitoring using drone imagery and ground sensors that provides real-time treatment recommendations to farmers.", futureProjects: "Automated greenhouse systems using AI to enable year-round high-value crop production in any African climate zone.", skills: ["Precision Ag", "Drone Tech", "AI/ML", "Sensor Networks"], contactEmail: "jacques@smartfarm.rw", contactPhone: "+250 789 345 678", linkedIn: "linkedin.com/in/jacquesndayisaba", twitter: "@jacquesndayisaba", seed: 142, gender: "man" },
{ name: "Yvonne Mensah-Bonsu", role: "VP Operations", company: "SupplyChainAI", industry: "Logistics", country: "Ghana", city: "Tema", bio: "Supply chain expert using AI to optimize cross-border trade logistics and reduce the cost of moving goods across Africa.", achievements: "Optimized logistics for 1000+ businesses. Reduced shipping costs by 35%. AfCFTA digital trade pilot partner.", currentProjects: "AI-powered customs and trade compliance platform that automates cross-border documentation and predicts clearance times.", futureProjects: "Autonomous supply chain orchestration platform using AI to coordinate multimodal transport across African trade corridors.", skills: ["Supply Chain", "AI Optimization", "Trade Compliance", "Operations"], contactEmail: "yvonne@supplychainai.gh", contactPhone: "+233 26 567 8901", linkedIn: "linkedin.com/in/yvonnemensahbonsu", twitter: "@yvonnemensah", seed: 143, gender: "woman" },
{ name: "Abdoulaye Sow", role: "Founder", company: "TelecomAI Senegal", industry: "Telecommunications", country: "Senegal", city: "Dakar", bio: "Telecom innovator using AI to optimize mobile network performance and expand connectivity across West Africa.", achievements: "Improved network coverage for 5M+ users. Partnerships with Orange and MTN. ITU Young Innovator Award.", currentProjects: "AI network optimization that predicts and prevents outages, dynamically allocating bandwidth based on real-time demand patterns.", futureProjects: "AI-powered community mesh networks that extend internet access to remote areas without traditional cell tower infrastructure.", skills: ["Telecom", "Network AI", "5G", "Rural Connectivity"], contactEmail: "abdoulaye@telecomai.sn", contactPhone: "+221 77 567 8901", linkedIn: "linkedin.com/in/abdoulayesow", twitter: "@abdoulayesow", seed: 144, gender: "man" },
{ name: "Chioma Nwosu", role: "Chief Revenue Officer", company: "AdTechAI Africa", industry: "Advertising", country: "Nigeria", city: "Lagos", bio: "Digital advertising pioneer using AI to connect African brands with consumers through hyper-personalized, culturally relevant campaigns.", achievements: "Managed $50M+ in African ad spend. AI ad platform serving 200+ brands. Doubled client conversion rates. Cannes Lions jury member.", currentProjects: "AI creative optimization platform that generates and tests culturally relevant ad variations across African markets in real-time.", futureProjects: "Predictive consumer behavior platform using AI to map purchasing patterns across Africa's emerging middle class.", skills: ["AdTech", "AI Personalization", "Marketing", "Data Analytics"], contactEmail: "chioma@adtechai.ng", contactPhone: "+234 811 234 5678", linkedIn: "linkedin.com/in/chiomanwosu", twitter: "@chiomanwosu", seed: 145, gender: "woman" },
{ name: "Tshepo Molefe", role: "Founder & CEO", company: "MusicAI Africa", industry: "Music & Entertainment", country: "South Africa", city: "Johannesburg", bio: "Music tech visionary using AI to discover, produce, and distribute African music to global audiences.", achievements: "AI-discovered 50+ now-signed artists. Platform streaming 100M+ plays monthly. Sony Music partnership. Grammy consideration.", currentProjects: "AI music production tools that help African artists create professional-quality tracks using their unique sound signatures.", futureProjects: "AI-powered global music distribution platform that automatically adapts African music for different market preferences worldwide.", skills: ["Music Tech", "AI Audio", "Distribution", "Artist Development"], contactEmail: "tshepo@musicai.co.za", contactPhone: "+27 73 890 1234", linkedIn: "linkedin.com/in/tshepomolefe", twitter: "@tshepomolefe", seed: 146, gender: "man" },
{ name: "Adama Keita", role: "Director of Engineering", company: "HealthChain Mali", industry: "Healthcare", country: "Mali", city: "Bamako", bio: "Health informatics expert building AI-powered health record systems connecting clinics across francophone West Africa.", achievements: "Digitized health records for 2M+ patients. Connected 500+ clinics. WHO Digital Health award. Partnership with MSF.", currentProjects: "AI-powered patient triage system that helps community health workers in remote areas make better diagnostic decisions.", futureProjects: "Federated AI health intelligence network enabling disease surveillance and early outbreak detection across West Africa.", skills: ["Health Informatics", "AI Diagnostics", "Blockchain", "Public Health"], contactEmail: "adama@healthchain.ml", contactPhone: "+223 66 456 7890", linkedIn: "linkedin.com/in/adamakeita", twitter: "@adamakeita", seed: 147, gender: "woman" },
{ name: "Peter Odhiambo", role: "CEO", company: "InsurTech East Africa", industry: "Insurance", country: "Kenya", city: "Nairobi", bio: "Insurance innovator building parametric insurance products for climate-vulnerable African communities using AI weather prediction.", achievements: "Protected 500,000+ farmers against weather risks. $20M+ in claims paid. Partnership with Swiss Re. InsurTech 100.", currentProjects: "AI-powered parametric crop insurance that uses satellite data and weather models to automatically trigger payouts during drought or flood events.", futureProjects: "Continental AI climate risk platform providing real-time risk assessments for infrastructure projects across Africa.", skills: ["InsurTech", "Climate AI", "Parametric Insurance", "Data Science"], contactEmail: "peter@insurtechea.co.ke", contactPhone: "+254 712 345 678", linkedIn: "linkedin.com/in/peterodhiambo", twitter: "@peterodhiambo", seed: 148, gender: "man" },
{ name: "Nana Ama Asare", role: "Founder", company: "BeautyAI Ghana", industry: "Beauty & Cosmetics", country: "Ghana", city: "Accra", bio: "Beauty tech entrepreneur using AI to create personalized skincare solutions for diverse African skin tones and types.", achievements: "500,000+ skin analyses performed. AI-formulated products in 5,000+ stores. Sephora Africa partnership. $4M raised.", currentProjects: "AI skin analysis app that provides personalized skincare routines and product recommendations for African skin types.", futureProjects: "AI-powered cosmetics manufacturing that creates custom-formulated products on demand based on individual skin profiles.", skills: ["Beauty Tech", "AI Personalization", "D2C", "Product Development"], contactEmail: "nana@beautyai.gh", contactPhone: "+233 54 678 9012", linkedIn: "linkedin.com/in/nanaamaasare", twitter: "@nanaamaasare", seed: 149, gender: "woman" },
{ name: "Lamine Touré", role: "Managing Director", company: "RoboFarm West Africa", industry: "Agriculture", country: "Guinea", city: "Conakry", bio: "Agricultural robotics entrepreneur deploying AI-guided farming robots to transform West African agriculture.", achievements: "Deployed 200+ farming robots. Increased productivity by 300%. Partnership with FAO. CTA Pitch AgriHack winner.", currentProjects: "AI-controlled autonomous weeding and harvesting robots adapted for smallholder farm conditions in West Africa.", futureProjects: "Swarm robotics for large-scale African agriculture using AI coordination to manage hundreds of farm robots simultaneously.", skills: ["Agri Robotics", "AI Navigation", "Mechanical Engineering", "Farming"], contactEmail: "lamine@robofarm.gn", contactPhone: "+224 628 567 890", linkedIn: "linkedin.com/in/laminetoure", twitter: "@laminetoure", seed: 150, gender: "man" },
];

export const seedMembers = mutation({
args: {},
returns: v.null(),
handler: async (ctx) => {
// Check if demo members already seeded
const existing = await ctx.db.query("users").take(60);
const demoExists = existing.some((u: any) => u.isDemo === true);
if (demoExists) return null;

for (const member of DEMO_MEMBERS) {
const imageUrl = `https://api.a0.dev/assets/image?text=${encodeURIComponent(`portrait photo of a ${member.gender === 'woman' ? 'female' : 'male'} ${member.country} professional, ${member.role} in ${member.industry}, ${member.name}, studio headshot, business attire, natural lighting`)}&aspect=1:1&seed=${member.seed * 7}`;

await ctx.db.insert("users", {
name: member.name,
image: imageUrl,
email: `${member.name.toLowerCase().replace(/[^a-z]/g, '')}@demo.aoe.africa`,
role: member.role,
company: member.company,
industry: member.industry,
country: member.country,
city: member.city,
bio: member.bio,
achievements: member.achievements,
currentProjects: member.currentProjects,
futureProjects: member.futureProjects,
skills: member.skills,
contactEmail: member.contactEmail,
contactPhone: member.contactPhone,
linkedIn: member.linkedIn,
twitter: member.twitter,
website: `www.${member.company.toLowerCase().replace(/[^a-z]/g, '')}.africa`,
interests: ["AI", "Innovation", "Africa"],
isDemo: true,
onboarded: true,
});
}

return null;
},
});

export const updateDemoImages = mutation({
args: {},
returns: v.null(),
handler: async (ctx) => {
const allUsers = await ctx.db.query("users").collect();
const demoUsers = allUsers.filter((u: any) => u.isDemo === true);

const memberMap = new Map(DEMO_MEMBERS.map(m => [m.name, m]));

for (const user of demoUsers) {
  const member = memberMap.get(user.name);
  if (member) {
    const imageUrl = `https://api.a0.dev/assets/image?text=${encodeURIComponent(`portrait photo of a ${member.gender === 'woman' ? 'female' : 'male'} ${member.country} professional, ${member.role} in ${member.industry}, ${member.name}, studio headshot, business attire, natural lighting`)}&aspect=1:1&seed=${member.seed * 7}`;
    await ctx.db.patch(user._id, { image: imageUrl });
  }
}

return null;
},
});